project:
  type: book
  output-dir: ../docs

book:
  title: "stats_notes"
  author: "Jane Doe"
  date: "01/12/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - Clinical Trials.qmd
    - survival.qmd
    - survival_regression.qmd
    - linear_models.qmd
    - glm.qmd
    - misc_topics.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
