# Survival


The first thing we are interested in is setting a baseline for the explanatory variables $\textbf{x}$. Where $\textbf{x}$ becomes the zero vector $\textbf{0}$. Eg. $\textbf{x} = (0,0,0...,0)$. 

It is very common for age to be standardised around some age of interest. Eg 50, so all ages would be given as 5, -10, etc which equates to 55 and 40.

The two common methods are :

- Accelarated Failure Time (AFT)
- Proportional Hazards (PH)

## AFT

### Two Group Example

In the simplests case we model survival times $T$ as a random variable. But with two groups we want to model them both as seperate RVs. Where the baseline RV is $T_0$ and the treatment (or other covariate) is given by $T_1$. As we now have times we can therefore model survivor functions $S$. However in AFTs we don't want $S_0$ and $S_1$ we want a single survivor function that is scaled.

We therefore look to the following:

$\text{Group 0 :   } S(t ; x_i=0) = P(T_0>t) = S_0(t))$
$\text{Group 1 :   } S(t ; x_i=1) = P(T_1>t) = P(\frac{T_0}{\psi}> t) = P(T_0>\psi t) = S_0(\psi t))$

So $\psi$ "accelrates time" and hence AFT and so the RVs are related by $T_1 = \frac{T_0}{\psi}$ and so $S_1(t) = S_0(\psi t)$.

Thinking back to graphing, any multiplier of a function value is a stretch in x, whose magnitude is the reciprical. So a $\psi >1$ will shrink survival time by $\frac{1}{\psi}$ and a $\psi <1$ will extend survival time.

So $\psi >1$ accelrates time for the patient (so they are more likely to die faster). Less than one Deaccelerates!

> Scale factor is $\frac{1}{\psi}$ , less than 1 means better survival times for the patient

So $\psi$ is a function of $\textbf{x}$, all of our covariates, which determine the "acceleration"

### Generalising to two groups

Instead of now having a $\psi$ to turn on and off we now require $\psi(\textbf{x})$ so that we can create a scaling factor for each individual. We therefore assume that (Where $S_0$ is $S(t)$ at the baseline consitions where $\textbf{x} = \textbf{0}$):

$S(t;\textbf{x}) = S_0(t\psi(\textbf{x}))$

From this it can be shown that the following are true:

$f(t;\textbf{x}) = f_0(t\psi(\textbf{x}))\psi(\textbf{x})$

$h(t;\textbf{x}) = h_0(t\psi(\textbf{x}))\psi(\textbf{x})$

This can be derived by showing that that $t$ being multiplie by $\psi$ and has $S_0$ applied to it as a function. We know the relationship between the survival function and the density fuinction. $S(t) = 1- F(t)$ differentiatiing we get negative density function. A function of a function, means that we need to use the chain rul and therefore gets the above. From the desnity we can get the hazard. TODO : Write out derivation. More details can be found at 25mins, 8/12. 

So again:
$T = \frac{T_0}{\psi(\textbf{x})}$

We are yet to define $\psi(\textbf{x})$ but tow conditions must be met:

- $\psi(\textbf{x})\geq 0$, so cannot have a negative time
- $\psi(\textbf{0}) = 1$, so that the basline has no strethcing effects. 

From this a naturual choice is (it could be any functiion though):

${\psi(\textbf{x})} = \exp(-\beta'\textbf{x})$

This gives us our parameters, but excludes the intercept terms. Recalling $T = \frac{T_0}{\psi(\textbf{x})}$ then 

$E[T] = \exp(\beta'\textbf{x})E[T_0]$

If $\beta_i x_i$ is positive then the expected survival time increases (good fro patient)

### Exponetial Case

Using the above we can therefore start to create an exponential AFT. We already know that for the exponential distribution:

Property| equation | AFT
-----|-----|----
$S(t)_0$|$e^{-\lambda t}$ | $S(t;\textbf{x}) = \exp(-\lambda t e^{-\beta'\textbf{x}})$
$h(t)_0$ | $\lambda$ | $\lambda e^{-\beta'\textbf{x}}$
$f(t)_0$|$\lambda e^{-\lambda t}$ | $\lambda e^{-\beta'\textbf{x}} \exp(-\lambda t e^{-\beta'\textbf{x}})$

So if $\textbf{x}_i$ is a p dimensional vector of explanatory variables then we ca n by MLE find p+1 parameters $(\lambda, \beta_1, \beta_2...\beta_p)$.

MLE is found by usual method, get derivative, set to 0, solve iteratively. $\hat{\lambda}$ and $\hat{\beta}$ are found any by the asymptopic properties of the MLE we know that:

$\hat{\lambda} \sim N(\lambda, \text{Var}(\hat{\lambda}))$

We can obtain $\text{Var}(\hat{\lambda}))$ from the expected/observed stuff covered in chapter 3 (TODO: find this out!)

#### Final model

If we are extra explicit with $\lambda_0$ we can say that $T_0 \sim \text{exp}(\lambda_0)$ so $S(t;\textbf{x}) = \exp(-\lambda_0 t e^{-\beta'\textbf{x}})$. Then it is more convinient to say that  $\lambda_0 = \exp(-\beta_0)$

Then we can lift the $\lambda$ into the exponent. Thus:

$S(t;\textbf{x}) = \exp(- t e^{(-(\beta_0 + \beta_1\textbf{x}_1 +  \beta_2\textbf{x}_2 ...))})$

This then looks alot like $e^{-t\lambda}$ but we now have $e^{-t\lambda(\textbf{x})}$ and so we can conclude:

$T \sim exp(\lambda(\textbf{x}))$ 

So $\lambda(x) = exp(-(\beta_0 + \beta_1\textbf{x}_1 +  \beta_2\textbf{x}_2 ...))$

And from standard properties we therefor know that $E[T] = \frac{1}{\lambda(\textbf{x})}$ and therefore thre MLE fo the mean is:

$\frac{1}{\hat{\lambda}(x)} = exp(\beta_0 + \beta_1\textbf{x}_1 +  \beta_2\textbf{x}_2 ...)$

> $\lambda_0 = \exp(-\beta_0)$ or $\lambda_0 = \exp(-\text{Intercept})$ in `survreg`

### Weibull

In R we use the following implementation of the weibull distribution, it's survivor function is as follows:

$S(t) = \exp{\(\lambda t )^{\gamma}}$

SO repeating the same steps as for the exponential we can say that the RV $T_0$ is:

$T_0 \sim \text{Weibull}(\lambda_0, \gamma)

Add the scalling factor:

$S(t;\textbf{x}) = exp(-(\lambda t e^{-\beta ' \textbf{x}})^{\gamma})$

Agian let $\lambda_0 = exp(-\beta_0)$

$S(t;\textbf{x}) = exp(-( t e^{-(\beta_0  + \beta_1 x_1 + \beta_2 x_2 ...)})^{\gamma})$

So $\lambda(\textbf{x}) = e^{-(\beta_0  + \beta_1 x_1 + \beta_2 x_2 ...)}$

The rate $\gamma$ is unaffected by the covariates, so only $\lambda(\textbf{x})$ is required.

### Testing Exp vs Weibull 

The defualt distribution in `survreg` is the weibull.

It will also report the log(scale) in the summary. This is a test that $H_0 \text{ : log(scale)} = 0$, basically whether $\gamma = 1$ as $\gamma = \frac{1}{scale}$. If we don't reject probably better to stick with the exponential as it is the simpler model.

## Proportional Hazards

In AFTs we were concerned with scaling time by $S(t;\textbf{x}) = S_0(t\psi(\textbf{x}))$, so survivor function depends on $\textbf{x}$.

In proportional hazards, the hazard function depends on \textbf{x} through the hazard function so. Agian we consider the baseline $h_0$ where the covariates $\textbf{x}$ are the zero vector $\textbf{0}$

$h(t;\textbf{x}) = \psi(\textbf{x};\beta) h_0(t)$

So again it's just deviation from the baseline. Again therefore we need a sensible function. There is only one constraint here and that is $\psi(\textbf{x}=0;\beta)$ must equal 1. So

$\psi(\textbf{x};\beta) = e^{\beta'\textbf{x}}$

Note that in AFT the exponent is negative, whereas it is positive here. We could use negative in AFT to make it consistent with the other parameter estimates, eg lambda as the intercept. A negative here would make it harder to interpret the hazards. 

### Why is it called proportional hazards

The hazard ratio is independent of time. As the baseline hazard cancels we are left with a time invariant ratio.

$\frac{h(t;x_1)}{h(t;x_2)} = \frac{h_0(t)e^{\beta_1 x_1}}{h_0(t)e^{\beta_2 x_2}} = \frac{e^{\beta_1 x_1}}{e^{\beta_2 x_2}}$

The first part is reffered to as the hazard ratio.

This is a strong assumption, which we must make sure to check.

### Advantage/Disadvantage

Advantages:

- We don't have to make assumptions on the underlying distribution of the baseline hazard/survival functions. This is mitigates some of the strong assumptions required for AFTs (Weibull vs Exp, etc)
- We are directly modelling the effect of the covariate on the hazard. To understand teh effects on hazard we just have to look at the signs of the covariates. In AFTs however it is not alwatys obvious and needs further calculation.

Disadvantages:
- As we haven't specified a $h_0$ then given a vector of patient characteristics it it not possible to actually specify the hazard.

If you are just interested in which covariates effect hazard/survival then PH is fine. If you want to want to actually compute probabilities of survival/times, expectations, etc then AFTs are required. So for instance in a PH model you would be able to say:

- smoking triples hazard relative to not
- treaetment halves hazard relative to placebo

However you could not say that smoking 10 cigs a day decrease expected survival time by 2  or probability of a cancer paitient surving more than two years on new meds is 0.6.

### Estimating $\beta$

We use likeihood methods. However notrmally we would say that 

$Likelihood = \Pi^n_{i=1} f(t_i;\textbf{x}_i)^{\delta_i} S(t_i ; \textbf{x}_i)^{1-\delta_i}$

This is also equal to (as $f(t) = h(t)S(t)$)

$Likelihood = \Pi^n_{i=1} h(t;\textbf{x})^{\delta_i} S(t_i ; \textbf{x}_i)$

Where $t_i$ is the min(Failure time, time of right censor) and $\delta_i$ is the indicator function where 1=death, 0 = censor.

However in PH we havent specified $h_0(t)$ so MLE isn't possible. We therefore hae to use partial likelihood.

#### Partial Likelihood

If we know the times of which people died, then we want to understand the probability that they died in that particular observed order order.

$P(\text{Death})  \propto h$

TODO : review partial likelihood!

### Intrepreting R output

The wald score is the coeff/S.E. This is standard normal. It's square is the $\chi^2_1$ which is useful in multi-level factors. 

For an set of covariates $\textbf{x} = (x_1, x_2, x_3....)'$ you will get the the following hazard:

$h(t;\textbf{x}  = h_0(t)e^{\beta_1 x_1 + \beta_2 x_2 ...}$.

Where you havea two level factopr Eg treatment. This becomes a binary case of x = 0 or 1. Therefore if we calculate the hazard for both case we get (assuming treatment has been set as the first variable and A = 0, B =1)

$\text{Treatment A :} $h(t;\textbf{x}  = h_0(t)e^{\beta_1(0) + \beta_2 x_2 ...}$

$\text{Treatment B :} $h(t;\textbf{x}  = h_0(t)e^{\beta_1(1) + \beta_2 x_2 ...}$.

And if we calculate the hazard ratio of $\frac{\text{Treatment B}}{\text{Treatment A}}$ then the terms cancel to leave only $e^{\beta_1}$. And so this is simply the hazard ratio for treatment on these covariates. This in turn means that the coeffieicnt itself is the log of the hazard ratio. 


#### Significance

By asymptopic variance of the MLE

$\hat{\beta} \sim N(\beta, s.e.(\hat{\beta})^2)$

So if you have either a two factor or continuous covariate you can compare either 

- the $\hat{\beta}/s.e.(\hat{\beta})$ to a $N(0,1)$ 
- or  $(\hat{\beta}/s.e.(\hat{\beta}))^2$ to a $\chi_1^2$ 

Or where you have $k >2$ factors you do the following:

- Calculate the $\chi_i^2 = (\hat{\beta}_i/s.e.(\hat{\beta}_i))^2$ for each of the k-1 variables
- $\sum^{k-1}_{i=1}\chi_i^2$ and compare to the $\chi_{k-1}^2$ dist.

#### Process - Binary


- Significance 
- Direction
- Quantify

Say we are interested in a treatment B and A where. B is 1 and A is 0 in the model. It is $\beta_1$ in the model.

The first look at $e^{\beta_1} = \frac{h{t;x_1=1}}{t;x_1=0}$:

- If $e^{\beta_1} <1$ Then the factor with value 1 (often the treatment B) **decreases** the hazard **relative** to teatment A
- If $e^{\beta_1} >1$ Then the factor with value 1 (often the treatment B) **Increases** the hazard **relative** to teatment A

We can put a CI on the Hazard ratio by taking the $e^{\hat{\beta_1} \pm 1.96(s.e.(\hat{\beta_1}))}$. As it is a monotonic transform it holds.

The ratio can be directly reported as a percentage which is often easier for audience to understand. So a CI of hazard ratio 0.25 to 0.75 would be:

"Relapse Hazard on Treatmnt B is likley to be between 25% ad 75% of realpse hazard on Treatment A."

#### Process - Continuous

In the case of the continuous what were are doing is calulating the following hazard ratio (this example used heart volume):

$\frac{h(t; \textbf{x}_4 = volume + 1)}{h(t; \textbf{x}_4 = volume)}$

So how does hazard increase when a continuous unit increase by one. Which much like the hazard ratio for a bianry case you will get alot of cancellation. Obviously the other covariates just cancel based on the baseline and:

$\frac{e^{\beta_4(x_4+1)}}{e^{\beta_4(x_4)}} = e^{\beta_4} $

#### Process - Multi level factors

Take k-1 factors and compute the available $\chi^2$ sum them and compare to the $\chi^2_{k-1}$. Remeber the baseline is just absorbed into the intercept like any linear model.

Remember $\chi^2$ is one sided and therefore compare directly to 0.95 and not 0.975.

#### In the exam/IRL

> If you are asked to **Interpret the output uou must do the following:
>
> - Significance : Does p-value drop below threshhold
> - Direction : Is hazard increased or decreased relative to the baseline
> - Quantify : Give a 95% CI for the hazard ratio.




TODO:

- Go through and derive log-log
- Do the residual stuff
- tito correction?
- Revisit entire likelihood partial aspect 14:00 - 30:20 last lecture
